Feature/sched 26
appNG/appng-scheduler pull request #1
Opened 2018-11-16 09:02 UTC by stuemke

new feature to record job executions.

2018-11-16 13:11 UTC, madness-inc commented on src/main/java/org/appng/application/scheduler/job/JobRecordHouseKeepingJob.java
> + */
Why not use lombok's @Data?

2018-11-16 13:13 UTC, madness-inc commented on src/main/java/org/appng/application/scheduler/service/RecordsRestController.java
> +	@Autowired
use constructor injection, makes getter/setter obsolete

2018-11-16 13:14 UTC, madness-inc commented on src/main/java/org/appng/application/scheduler/model/JobResult.java
> +
Wyh not use @Data?

2018-11-16 13:15 UTC, madness-inc commented on src/main/java/org/appng/application/scheduler/model/JobRecord.java
> +
Why not use @Data?

2018-11-16 13:18 UTC, madness-inc commented on application-home/beans.xml
> +				<entry key="cronExpression" value="${indexExpression}" />
indexExpression is used for lucene indexing. Use dedicated property?

2018-11-16 13:20 UTC, madness-inc commented on src/main/java/org/appng/application/scheduler/business/Records.java
> +public class Records implements DataProvider {
Define as @Component and use constructor injection

2018-11-16 13:21 UTC, madness-inc commented on src/main/java/org/appng/application/scheduler/business/SchedulingController.java
>  public class SchedulingController extends SchedulerAware implements ApplicationController {
Define as @Component and use constructor injection (remove from beans.xml)

2018-11-16 13:22 UTC, madness-inc commented on src/main/java/org/appng/application/scheduler/business/Records.java
> + * Copyright 2011-2017 the original author or authors.
must be 2011-2018

2018-11-16 13:23 UTC, madness-inc requested changes
see comments

2018-11-16 15:55 UTC, stuemke commented on src/main/java/org/appng/application/scheduler/business/Records.java
> +public class Records implements DataProvider {
done. see latest commit

2018-11-16 15:55 UTC, stuemke commented on src/main/java/org/appng/application/scheduler/business/SchedulingController.java
>  public class SchedulingController extends SchedulerAware implements ApplicationController {
done. see latest commit

2018-11-16 15:56 UTC, stuemke commented on src/main/java/org/appng/application/scheduler/job/JobRecordHouseKeepingJob.java
> + */
done. see latest commit

2018-11-16 15:57 UTC, stuemke commented on src/main/java/org/appng/application/scheduler/model/JobResult.java
> +
done. see latest commit. But you have to be carefule using @ Annotations in comments. Maybe you can change the one above?

2018-11-23 12:57 UTC, madness-inc commented on src/main/java/org/appng/application/scheduler/service/JobRecordService.java
> +	private boolean addFiler(String filterName, String operator, String filterValue, StringBuilder sql,
Shoud be addFil**t**er

2018-11-23 12:57 UTC, madness-inc commented on src/main/java/org/appng/application/scheduler/service/JobRecordService.java
> +	private boolean addFiler(String filterName, String operator, String filterValue, StringBuilder sql,
Shoud be addFil**t**er

2018-11-23 13:00 UTC, madness-inc commented on src/main/java/org/appng/application/scheduler/business/Records.java
> +	public JobRecordService getJobRecordService() {
Getter/setter not need due to constructor injection

2018-11-23 13:22 UTC, stuemke commented on src/main/java/org/appng/application/scheduler/business/Records.java
> +	public JobRecordService getJobRecordService() {
getter and setter have been removed

2018-11-23 13:23 UTC, stuemke commented on src/main/java/org/appng/application/scheduler/service/JobRecordService.java
> +	private boolean addFiler(String filterName, String operator, String filterValue, StringBuilder sql,
Typo has been corrected

2018-11-26 13:09 UTC, madness-inc commented on pom.xml
> +			<plugin>
Use appNG Maven Plugin instead
https://github.com/appNG/appng/tree/appng-1.17.1/appng-maven-plugin

2018-11-26 13:31 UTC, stuemke commented on pom.xml
> +			<plugin>
Done. Using appng-maven-plugin now

2018-11-26 14:02 UTC, madness-inc approved these changes
Great work!

2018-11-26 14:04 UTC, madness-inc approved these changes
Great Work!

2018-11-26 14:05 UTC, merged